language: python
python:
    - "3.5"
    - "3.8"
    - "nightly"
jobs:
    allow_failures:
        - python: "nightly"
install:
    - pip install flake8 mypy pytest pytest-cov
script:
    - mypy .
    - python -m pytest --cov=.
    - flake8